// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Rovecom.TicketConnector.Domain;
using System;

namespace Rovecom.TicketConnector.Domain.Migrations
{
    [DbContext(typeof(ConnectorContext))]
    [Migration("20180504134217_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rovecom.TicketConnector.Domain.Entities.ProjectEntity.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Rovecom.TicketConnector.Domain.Entities.WorklogEntity.Worklog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<double>("KilometresCovered");

                    b.Property<int?>("MspTechnicianId");

                    b.Property<int?>("ProjectId");

                    b.Property<DateTime>("WorkEndedDateTime");

                    b.Property<DateTime>("WorkStartedDateTime");

                    b.HasKey("Id");

                    b.HasIndex("MspTechnicianId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Worklog");
                });

            modelBuilder.Entity("Rovecom.TicketConnector.Domain.MSP.MspTechnicianEntity.MspTechnician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("MspTechnician");
                });

            modelBuilder.Entity("Rovecom.TicketConnector.Domain.Entities.WorklogEntity.Worklog", b =>
                {
                    b.HasOne("Rovecom.TicketConnector.Domain.MSP.MspTechnicianEntity.MspTechnician", "MspTechnician")
                        .WithMany()
                        .HasForeignKey("MspTechnicianId");

                    b.HasOne("Rovecom.TicketConnector.Domain.Entities.ProjectEntity.Project")
                        .WithMany("ConnectorWorklogs")
                        .HasForeignKey("ProjectId");
                });
#pragma warning restore 612, 618
        }
    }
}
